export { default as loggerPlugin } from './logger'
export { default as persistPlugin } from './persist'
export { default as routerPlugin } from './router'
export { default as notificationsPlugin } from './notifications'
export { notificationsData as notificationsBinding } from './notifications/notifications.data'
